spring:
  application:
    name: slack
  datasource:
    url: jdbc:postgresql://localhost:5432/rush
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

slack:
  token: ${SLACK_API_TOKEN}
