server:
  port: 19091

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-slack-service
          uri: lb://user-slack-service
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
            - Path=/api/slack/**
        - id: order-delivery-service
          uri: lb://order-delivery-service
          predicates:
            - Path=api/orders/**
            - Path=api/deliveries/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/hubs/**
            - Path=/api/hubs-routes/**
        - id: company-product-service
          uri: lb://company-product-service
          predicates:
            - Path=api/products/**
            - Path=api/companies/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"