spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hub
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/