spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:postgresql://${HUB_DB_URL}
    username: ${HUB_DB_USERNAME}
    password: ${HUB_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${HUB_REDIS_HOST}
      port: ${HUB_REDIS_PORT}
      username: ${HUB_REDIS_USERNAME}
      password: ${HUB_REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/

naver:
  map:
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}
