spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: kangheeseung
    password: 1129
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/