spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
      use_sql_comments: true

server:
  port: 19040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
