server:
  port: 19020

spring:
  application:
    name: order-delivery-service

  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


# feign log
feign:
  client:
    config:
      default:
        loggerLevel: full
logging:
  level:
    com.rush.logistic : debug

# zipkin
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

# swagger
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: order-delivery-service/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

gemini:
  api:
    url: ${ORDER_GEMINI_URL}
    key: ${ORDER_GEMINI_KEY}

